



const GAME_VERSION = "Alpha 0.6.0"
const DEV_TOOLS = false;
var SPAWN_ENEMIES = true;
const LOAD_MENU = true;

const DISABLE_PARTICLES = false;
const HIDE_PLAYER = false;


// Can be removed
const IN_ITCH = false;

// Increases the draw distance
const IS_FILMING = false;

// Disables toolbar
const PICTURE_MODE = false;



const MAX_ENEMIES_IN_WORLD = 5;
const GEN_DUNGEONS = false;
const GEN_OLD_STYLE_WORLD = false;

/*
	For saving/loading
*/
let loggedIn = false;
let emailAccount = "null";
let sessionToken = "null";
let accountUID = "null";
let idToken = "null";


/*
	GEN_DUNGEON represents the new
	dungeon, not generated by portion.
*/
const GEN_SHOP = true;
const GEN_DUNGEON = false;
const GEN_WATER = true;

/*
	Set to 1.5 for 1080p
	Set to 1 for 720p (default)
*/
const canvas_multiplier = 1;
const start_volume = 0.2; //0.2;

/*
	The probability an enemy is spawned roughly every second.
*/
const SPAWN_RATE = 0.07;


/*
	Some information:

	In inventory, cursor coordinates are:
		cursorCoor[0], cursorCoor[1]

*/


